# Generated by Django 4.2.11 on 2025-02-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
